CREATE TABLE [DBO].[CUSTOMER](
   [ID]   INTEGER  NOT NULL KEY IDENTITY(1,1)
  ,[NAME] VARCHAR(50) NULL
  ,[TYPE] VARCHAR(11) NULL
PRIMARY KEY CLUSTERED ([ID] ASC)
);
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (1,'BAPCO','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (2,'MCSCWLL','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (3,'BMMI-BLS','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (4,'BMMI-NTM','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (5,'Al-Manaratain','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (6,'Haji Hassan Readymix','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (7,'Ahmed Sharif Furniture','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (8,'Deeko Bahrain','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (9,'AL Noor National School','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (10,'SPECTRUM CLEANING CO.','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (11,'UGA','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (12,'Bahrain Asphalt Company','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (13,'INTERCOL','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (14,'Bahrain Precast Concrete','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (15,'Ministry of Education','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (16,'Almoayyed_HE','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (17,'Bahrain Blocks Company','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (18,'Royal Court','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (19,'Yusif Bin Yusif Fakhro','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (20,'Bahrain Post Office','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (21,'Bahrain Pipes','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (22,'Bahrain Asphalt Garage','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (23,'LMRA','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (24,'RAAS OILFIELD SERVICES & SUPPLIES WLL','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (25,'Abdul Kareem Almannaie','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (26,'Lazer Car Wash & Lubricants','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (27,'SLRB','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (28,'Central Bank of Bahrain','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (29,'Mohammed Fakhroo','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (30,'Southern Area Municipality','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (31,'Zayani leasing - Northern Area Municipality','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (32,'Arabian Parts Company','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (33,'Al-Amal Services Co. W.L.L','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (34,'Almoayyed-RMD','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (35,'Abu Dawood Al Saffar Company','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (36,'AKM Security Solutions','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (37,'ARM Associates','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (38,'Mabani Al Bahrain','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (39,'MADAR BAHRAIN BUILDING MATERIALS','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (40,'Ministry of Work','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (41,'Al Sawadi Construction and Trading Company','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (42,'Ali Reza and Sons','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (43,'Bahrain Medical Center','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (44,'British American Topaco -YK','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (45,'General Secretariat of Cabinet','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (46,'Manama Sky','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (47,'Wasam properties company w.l.l','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (48,'Wasayef Contracting','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (49,'Zayani Leasing (MOIC)','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (50,'Abbas/Walla','Individual');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (51,'Alaa Matar','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (52,'Alleewan Properties & Cleaning Co.','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (53,'AlMansoori Workover Services','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (54,'ALMOAYYED MOTORS - FORD DIVISION','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (55,'ARABIAN CHEMICAL INDUSTRIES (ISOLA)','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (56,'Bahrain Medical Lab','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (57,'Bahrain Rubber','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (58,'Bahrain Special Technical Services (STS) Co. W.L.L.)','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (59,'Contra Tech Bahrain','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (60,'Express Car Care','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (61,'Gary','Individual');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (62,'HAFEERA GROUP','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (63,'Isa Cultural Center','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (64,'Munther Alshaikh','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (65,'Noora Al Kooheji','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (66,'Rise Land Tourist Transport','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (67,'Salah Abdulla (Private)','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (68,'Saleem Al-Kooheji','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (69,'Waheed Areena','Orgnization');
INSERT INTO [DBO].[CUSTOMER](ID,NAME,TYPE) VALUES (70,'YK Almoayyed & Sons','Orgnization');